version: "3.9"
services:
  sqlserver:
    env_file: "./env_variables.conf"
    environment:
      ACCEPT_EULA: Y

    image: mcr.microsoft.com/mssql/server:2017-CU31-ubuntu-18.04
    ports:
      - 1433:1433
      - 1444:1444

  dev_dotnet:
    build:
      context: .
      dockerfile: ci.Dockerfile
    depends_on:
      - sqlserver
    ports:
      - 4213:4213
